services:
  recaptcha.type:
    class: Videotech\RecaptchaBundle\Type\RecaptchaSubmitType
    tags: ['form.type']
    arguments:
      $key: '6LdmSiEbAAAAADIftD5zO_6Q7oQTINiDhilRMwIz'

#recaptcha:
#  key: 6LdmSiEbAAAAADIftD5zO_6Q7oQTINiDhilRMwIz
#  secret: 6LdmSiEbAAAAACVdLaeXD4dJdynAxDmvYvibztMi