#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path:       app_login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

captcha_routing:
      resource: "@CaptchaBundle/Resources/config/routing.yml"